import { Restaraunt } from "./types";

export const RestarauntState: Restaraunt[] = [
  {
    id: 1,
    name: "animals1",
    adress: "spb",
    hookah: true,
    animals: true,
    breakfast: true,
    vegan: true,
    avgPrice: 1200,
  },
  {
    id: 2,
    name: "animals2",
    adress: "spb",
    hookah: false,
    animals: false,
    breakfast: false,
    vegan: false,
    avgPrice: 1000,
  },
  {
    id: 3,
    name: "animals3",
    adress: "spb",
    hookah: false,
    animals: true,
    breakfast: false,
    vegan: false,
    avgPrice: 600,
  },
  {
    id: 4,
    name: "animals4",
    adress: "spb",
    hookah: false,
    animals: true,
    breakfast: false,
    vegan: true,
    avgPrice: 700,
  },
  {
    id: 5,
    name: "animals5",
    adress: "spb",
    hookah: true,
    animals: false,
    breakfast: false,
    vegan: true,
    avgPrice: 1500,
  },
  {
    id: 6,
    name: "animals6",
    adress: "spb",
    hookah: true,
    animals: false,
    breakfast: true,
    vegan: true,
    avgPrice: 1400,
  },
  {
    id: 7,
    name: "animals7",
    adress: "spb",
    hookah: false,
    animals: true,
    breakfast: false,
    vegan: false,
    avgPrice: 1300,
  },
  {
    id: 8,
    name: "animals8",
    adress: "spb",
    hookah: true,
    animals: false,
    breakfast: false,
    vegan: true,
    avgPrice: 1100,
  },
  {
    id: 9,
    name: "animals9",
    adress: "spb",
    hookah: false,
    animals: false,
    breakfast: false,
    vegan: false,
    avgPrice: 100,
  },
  {
    id: 10,
    name: "animals10",
    adress: "spb",
    hookah: true,
    animals: false,
    breakfast: false,
    vegan: true,
    avgPrice: 200,
  },
  {
    id: 11,
    name: "animals11",
    adress: "spb",
    hookah: false,
    animals: true,
    breakfast: false,
    vegan: true,
    avgPrice: 300,
  },
  {
    id: 12,
    name: "animals12",
    adress: "spb",
    hookah: false,
    animals: true,
    breakfast: false,
    vegan: false,
    avgPrice: 2000,
  },
  {
    id: 13,
    name: "animals13",
    adress: "spb",
    hookah: false,
    animals: true,
    breakfast: false,
    vegan: false,
    avgPrice: 2100,
  },
  {
    id: 14,
    name: "animals14",
    adress: "spb",
    hookah: false,
    animals: true,
    breakfast: false,
    vegan: true,
    avgPrice: 2200,
  },
  {
    id: 15,
    name: "animals15",
    adress: "spb",
    hookah: true,
    animals: false,
    breakfast: false,
    vegan: false,
    avgPrice: 150,
  },
  {
    id: 16,
    name: "animals16",
    adress: "spb",
    hookah: false,
    animals: false,
    breakfast: true,
    vegan: true,
    avgPrice: 2900,
  },
  {
    id: 17,
    name: "animals17",
    adress: "spb",
    hookah: false,
    animals: false,
    breakfast: true,
    vegan: true,
    avgPrice: 250,
  },
  {
    id: 18,
    name: "animals18",
    adress: "spb",
    hookah: true,
    animals: false,
    breakfast: false,
    vegan: false,
    avgPrice: 3000,
  },
  {
    id: 19,
    name: "animals19",
    adress: "spb",
    hookah: false,
    animals: true,
    breakfast: false,
    vegan: false,
    avgPrice: 350,
  },
  {
    id: 20,
    name: "animals20",
    adress: "spb",
    hookah: false,
    animals: false,
    breakfast: true,
    vegan: false,
    avgPrice: 550,
  },
  {
    id: 21,
    name: "animals21",
    adress: "spb",
    hookah: true,
    animals: true,
    breakfast: true,
    vegan: true,
    avgPrice: 3100,
  },
];
